### ISSUE TITLE
Pi camera has incorrect colors

### ISSUE THREAD

**Issue by necrosato** [necrosato/home-alert#71]
When installing using pi cam I noticed that the colors are off. I know my pi cam works because I tested ```raspistill -o /tmp/test.jpg --width 1920 --height 1080``` and got a picture with correct results.

**Comment by necrosato** [comment]
![](https://docs.google.com/document/d/e/2PACX-1vQCRykqOows9bQ5j8xVYtVb7Gg3pXf70csZx1xS8kx_cqXsIThFoy6ISNZ3bf23axkB_a7ObVA4G3oJ/pub)

**Comment by necrosato** [comment]
Discovered that the issue does not appear at 720p, but does appear at 1080p.

**Comment by necrosato** [comment]
@margielamadman does this happen with your pi cam?

**Comment by margielamadman** [comment]
> @margielamadman does this happen with your pi cam?

Don't have a pi cam to test with right now.

I could check to see if fswebcam and HomeAlertCamera produce different results using the USB webcam.

**Comment by necrosato** [comment]
@margielamadman that would be great. I wanted to run that test but my usb webcam is 720 p.

**Comment by margielamadman** [comment]
How did you install opencv?

**Comment by necrosato** [comment]
@margielamadman Using apt

**Comment by necrosato** [comment]
Fixed via #82 . Open cv caused pain and misery in more ways than one.
